### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by vendethiel** [michaelficarra/commonjs-everywhere#11]
Hi! Nice module, tried to integrate it on my script but on Windows, it compiles like this : 

``` js
    require.define('/modules\\jumps.ls', function (module, exports, __dirname, __filename, process) {
        require('/modules\\jumps\\top.ls');
        if (!QS('.player-name')) {
            require('/modules\\jumps\\login.ls');
        }
    });
```

**Comment by michaelficarra** [comment]
That looks fine to me. What's the problem?

**Comment by vendethiel** [comment]
I'd like the diff not to go crazy when somebody with *nix compiles it

**Comment by vendethiel** [comment]
Btw, I love the way brunch's require works.
`require 'abc'` will try to require from root too. Same as `require '/abc'` (I'd be fine with both, but spamming `../` feels a bit unreadable to me)

**Comment by michaelficarra** [comment]
@Nami-Doc:
1. That makes sense. I will look into changing it.
2. That should work now. That's what this line is for: https://github.com/michaelficarra/commonjs-everywhere/blob/7ce2f7c956076d9aff3fd66478d67e990020e1a6/src/index.coffee#L82

**Comment by vendethiel** [comment]
2) Maybe that's also because of this `/` and `\\` path nonsense too
Am getting `cannot find module "utils/toCamelCase" in "C:\Users\blah\ls\wbh\src\shared`.
Tried with `root` to "/", __dirname + "/",  __dirname + "/src", __dirname + "\src".

**Comment by michaelficarra** [comment]
@Nami-Doc: Are you using `master`? I fixed relative requires this morning. They were broken as of `0.2.0`.

**Comment by vendethiel** [comment]
Ah, no, I took the last tag available

**Comment by vendethiel** [comment]
EDIT : this fixed it - my bad. Will leave open for 1)

And I'd love to know the filename that has the require issue.

**Comment by michaelficarra** [comment]
@Nami-Doc: require issue?

**Comment by vendethiel** [comment]
Ie, `cannot find module "foobar" in my\directory` is nice but I'd like to know _which file_ required foobar.

**Comment by michaelficarra** [comment]
Ah, that would be desirable. I thought about adding that information, but I figured it would create a less readable output. It also wasn't trivial, since I don't pass that information to the functions that do that lookup yet.

**Comment by vendethiel** [comment]
While I'm at it ... Is there a way to make this "speed up" ? It's already quite fast and I don't want to impose on you, but I'd like to be able to ctrl+s, reload chrome extensions and F5 directly. the module takes around 1s to compile everytime, and I'm looking for a cache solution.
I have my `watch` task, I could maybe `cjsify.createIndexFor __dirname` or something to pre-list all files, so that further build are taking as little time as possible :). Even if it's not that big of an issue now, that may be in the future.
And if you already have something like that but I just didn't read it, my bad!

**Comment by michaelficarra** [comment]
That would certainly be nice. A nice tool could watch a directory and keep the ASTs in memory, then only parse/regenerate the ones it needs when it sees changes. But I really couldn't see a necessity for something so complex. As you said, the tool is quite fast as is.

**Comment by vendethiel** [comment]
Not as fast as, save, alt-tab and F5 et voilà. As I quoted previously, brunch must do something like that because it's incredibly fast.

**Comment by michaelficarra** [comment]
After thinking about this some more, I think I'll stick with the current behaviour. You shouldn't be checking in these built files, anyway.
