### ISSUE TITLE
grunt plugin

### ISSUE THREAD

**Issue by benatkin** [michaelficarra/commonjs-everywhere#13]
A grunt plugin would make this part of a more complete workflow. When one gets written, a link to it in the README would be awesome.

**Comment by michaelficarra** [comment]
I looked into this, read through the documentation, installed the required packages, and even `grunt-init`ted a project, but damn. That project is just way too involved. Automation should be easy. I use a Makefile for specifying tasks with dependencies, and use a custom inode watcher for responding to filesystem events. If somebody wants to define a grunt plugin, I'll gladly link to it from the README. But this is far too much effort for me.

**Comment by tiye** [comment]
I want that grunt plugin too.. Grunt is to heavy though, we don't have an alternative yet.
And I do think Makefile is not easy for many JS programmers.

**Comment by benatkin** [comment]
Oh well, it's commonjs-everywhere's loss. Grunt will be just fine without it.

**Comment by michaelficarra** [comment]
@jiyinyiyong: I don't see why anybody would think Makefiles are hard: https://github.com/michaelficarra/CoffeeScriptRedux/blob/b08997d4bfb94dc0f531bbb5127b6c32cd7b8338/Makefile#L45-L60

**Comment by tiye** [comment]
Makefile is easy when it looks like Bash, but hard while there's are a lot of unfamiliar symbols.

``` make
lib/parser.js: src/grammar.pegjs bootstraps lib
    $(PEGJS) <"$<" >"$(@:%=%.tmp)" && mv "$(@:%=%.tmp)" "$@"
lib/bootstrap/parser.js: src/grammar.pegjs lib/bootstrap
    $(PEGJS) <"$<" >"$@"
lib/bootstrap/%.js: src/%.coffee lib/bootstrap
    $(COFFEE) -i "$<" >"$@"
bootstraps: $(BOOTSTRAPS) lib/bootstrap
    cp lib/bootstrap/* lib
lib/%.js: src/%.coffee lib/bootstrap/%.js bootstraps lib
    $(COFFEE) -i "$<" >"$(@:%=%.tmp)" && mv "$(@:%=%.tmp)" "$@"
```

https://github.com/michaelficarra/CoffeeScriptRedux/blob/b08997d4bfb94dc0f531bbb5127b6c32cd7b8338/Makefile#L33-L42

**Comment by vendethiel** [comment]
@benatkin how is that cjsify's loss ? What would you need grunt for, with cjsify in place ? Linting ?

**Comment by benatkin** [comment]
Linting, css (stylus/less/sass), image optimization, etc. They have quite a list of plugins: http://gruntjs.com/plugins

**Comment by vendethiel** [comment]
Sure, [cjsify can handle stylus, less, sass even as a commonjs module](http://github.com/qqueue/c4) or [just trap it to recompile using an one-liner stylus()](http://github.com/nami-doc/wowboardhelpers). At that point, I think that brunch could be a better fit (no node_modules, true, but bower usually does the job).

**Comment by hybrist** [comment]
Far from polished and I wouldn't want to maintain it (not really in love with grunt) but if anyone is interested: https://gist.github.com/jkrems/7983003
