### ISSUE TITLE
NPM registry download is huge

### ISSUE THREAD

**Issue by qqueue** [michaelficarra/commonjs-everywhere#21]
https://registry.npmjs.org/commonjs-everywhere/-/commonjs-everywhere-0.3.1.tgz is **28.4 MB**. Can't you make it any smaller?

**Comment by michaelficarra** [comment]
Hmm. Looks like that made it better, but not as small as it should be. Continuing to look into this.

**Comment by michaelficarra** [comment]
@qqueue: The package is down to 160KB now. Thanks for pointing this out.
