### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by vendethiel** [michaelficarra/commonjs-everywhere#22]
(from #11)

> As you said, the tool is quite fast as is.

Build time for me : 

```
cjsify : 1051ms
ls     : 220ms
hamlc  : 67ms
esprima: 37ms
AST->JS: 44ms
Total  : 1420ms
compiled script to wowboardhelpers.user.js
```

This is calculated [here](https://github.com/Nami-Doc/wowboardhelpers/blob/master/Slakefile#L110). The time spent in esprima, haml-coffee and livescript is _not_ included in the csify step. AST->JS is done after.

**Comment by michaelficarra** [comment]
Well, it is doing everything in serial; the async interface from #17 would allow the file reads to be parallelised. This would probably help performance a bit. I wonder where the bottleneck is. I don't know how to profile JS apps outside the browser.

**Comment by vendethiel** [comment]
Maybe add a way (`cached` flag?) to remember which file resolved to which for that root? Since I'm not throwing the instance when `watch`ing. Not sure how index building would work but that probably wouldn't be much use.

**Comment by michaelficarra** [comment]
What version are you using for this test? Can you try using `0.3.3` if you're not already?

**Comment by vendethiel** [comment]
Just updated. That's the same speed.

```
cjsify : 1110ms
ls     : 219ms
hamlc  : 52ms
esprima: 41ms
AST->JS: 45ms
Total  : 1469ms
compiled script to wowboardhelpers.user.js
```

**Comment by michaelficarra** [comment]
Well, crap. Any idea how I should profile this?

**Comment by vendethiel** [comment]
Not really. See https://github.com/qqueue/html5chan/commit/5a1013735f7aa21ad7aaa43a0c108f0674265f1b#commitcomment-2721329

**Comment by vendethiel** [comment]
http://dtrace.org/blogs/dap/files/2012/05/fluent.pdf

**Comment by vendethiel** [comment]
Just moved my root from `src/` to `/`, now I load things from `node_modules/` too and the time reduced to 500ms. I use more files than before. Not sure what's going on here. (updating from 0.3 to 0.5 shaved around 50ms)

**Comment by vendethiel** [comment]
https://github.com/dannycoates/node-inspector + node-gyp + https://github.com/dannycoates/v8-profiler maybe.
I'm afraid I use windows :(.

**Comment by vendethiel** [comment]
As for why I got to back to 1s (1.2s with async so that actually doesn't help), I just discovered the problem haha.
I have a 8k6 lines long library included. It takes 512ms to process (I suppose that's esprima). If I could only cache it :(. (I probably could override the .js handler to check the filename and return a cached version but meh)
Maybe for `node_modules/` things,mmh...

Log : https://gist.github.com/Nami-Doc/391fea731091e9645055 (this just wraps the handler call). I'd probably go back to 200ms if I could just return JS :p

**Comment by michaelficarra** [comment]
@Nami-Doc: You can cache it. That's what the CLI does when the `--watch` option is passed. Have you tried that yet?

**Comment by vendethiel** [comment]
I'm currently caching any js file (Nami-Doc/wowboardhelpers@b076f26554b868956730b2c63f7631bfd36955a5). I'm not sure what else you mean?

**Comment by vendethiel** [comment]
I could probably get a md5 hasher and only recompile on change. I'll love that to be in commonjs-everywhere tho :) (would not require me to override the `.js` handler and would clean up my bloated slakefile).

**Comment by vendethiel** [comment]
Okay, I implemented the md5 hasher, but you seem to be mutating the AST I'm passing because I get an `invalid require : require('blah', module)` error the second time I give you the same AST.

I still have "cjsify : 683ms". I'll try to profile it a bit more tomorrow, I should have time :-). I think that's the only "drawback" your tool has. (and I put that in quotes because all the other tools have the same problem, as far as I'm concerned)

**Comment by michaelficarra** [comment]
@Nami-Doc:

> I'm not sure what else you mean?

The CLI has a `--watch` flag that caches ASTs and only rebuilds touched files and their dependencies. It was added over a month ago in 7ad8239e6a06797ea52b9574b0ff5c921e8c0c8d.

> get a md5 hasher and only recompile on change

That seems like a great idea that could work in combination with the current watch caching. I will open an issue for that.

> Okay, I implemented the md5 hasher

Can you link me to your implementation?

> you seem to be mutating the AST I'm passing

Yep, I went with the mutating traversal of `estraverse` for performance reasons. I think it's the best choice.

**Comment by vendethiel** [comment]
Am reading your commit.

> Can you link me to your implementation?

I'll commit it by tomorrow - I want to cleanup my Slakefile. 144 lines for `build`/`watch` is FAR TOO BLOATED (well I'll probably remove timers now, I'll get to half the size haha)
My implementation is very basic.

``` ls
hashes = {}
cache = {}
cachecompile = (fn) ->
  (it, filename) ->
    esprima-parse if hashes[filename] is hash = md5 it
      cache[filename]
    else
      delete cache[delete hashes[filename]]
      hashes[filename] = hash
      cache[filename] = fn it.toString!, filename
```

then

``` ls
handlers:
  '.ls': cachecompile (src, filename) -> # ...
```

I probably could remove filename checking (if I have 2 times the same src (wut) I don't think that'll be a different language).

**Comment by vendethiel** [comment]
Okay, that's a clever one :-). I don't need to recompile all deps, tho, so I'll stay with that until you do #45 (or if I look at it, but I'd rather check time improvements)

**Comment by michaelficarra** [comment]
@Nami-Doc: Try out the improved `--watch` caching in `0.6.2`.

**Comment by vendethiel** [comment]
I don't use the CLI but I'll implement something like qqueue/c4@3a2ec54ba5c48117b69c073ed0c7aa216379e0f4

**Comment by vendethiel** [comment]
Awesome, awesome.

Avg 30ms for cjs (and 260ms for escodegen). Even faster than what I had before cjs !

Nami-Doc/wowboardhelpers@71659780393177af5d521cd50dcabbcd4df9dca6, thanks @qqueue
