### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by dwalters-zz** [michaelficarra/commonjs-everywhere#23]
At the moment, looks like circular dependencies aren't supported.  While ugly, it's something you run into from time to time.

The modules spec at http://wiki.commonjs.org/wiki/Modules/1.1.1 states:

> If there is a dependency cycle, the foreign module may not have finished executing at the time it is required by one of its transitive dependencies; in this case, the object returned by "require" must contain at least the exports that the foreign module has prepared before the call to require that led to the current module's execution.

I got it working by adding an additional `require.cache[file] = module$.exports;` before the `resolved.call` in the `PRELUDE`, but not sure if it's the best approach (and the tests aren't working on my system.)

**Comment by michaelficarra** [comment]
That sounds like a good solution.

**Comment by michaelficarra** [comment]
@dwalters: I've fixed it, just as you suggested. Upgrade to version `0.3.4`. Thanks for the bug report.

**Comment by dwalters-zz** [comment]
Awesome, thanks!
