### ISSUE TITLE
npm test not working

### ISSUE THREAD

**Issue by fulmicoton** [michaelficarra/commonjs-everywhere#25]
It would be nice to get "npm test" to work correctly, and add the project to Travis CI, etc.
At the moment it fails because of the broken symlinks in core/ when run locally.

Did I get something wrong?

**Comment by fulmicoton** [comment]
Ok sorry for this didn't catch the node submodule. 
For other people, git submodule update --init after cloning.

**Comment by michaelficarra** [comment]
Reopening to set up Travis CI.

**Comment by fulmicoton** [comment]
Cool!

I sent you a pull request with a working conf for Travis CI.
https://github.com/michaelficarra/commonjs-everywhere/pull/26
I hope it helps.

**Comment by michaelficarra** [comment]
Just enabled the Travis commit hooks for the repo. It should be running the tests and validating each commit now :smile:. Thanks again for this.

**Comment by michaelficarra** [comment]
:frowning: Never mind, the build fails: https://travis-ci.org/michaelficarra/commonjs-everywhere/jobs/5276425

Does travis CI not allow you to use the `fs` module or something? Tests all pass for me locally.
