### ISSUE TITLE
add watch flag to CLI for continuous builds on dependency change

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#31]
**original topic:** split dependency traversal out from cjsify to allow for fast, continuous builds

We might need to split up `cjsify` into `traverseDependencies` (or something) and `bundle`. This will allow us to give it an entry point of a single changed file, get back a mapping from new files to ASTs, merge it into a cache, re-bundle our cache, and re-output. The only problem I can see is that bundles will get monotonically larger because, as dependencies get removed, they will remain in new bundles.

**Comment by vendethiel** [comment]
> The only problem I can see is that bundles will get monotonically larger because, as dependencies get removed, they will remain in new bundles.

Just clean the cache, it won't cause any problem

**Comment by michaelficarra** [comment]
Sure, but how often? If we had a real dependency tree, we could figure out when something gets dropped and delete it from the cached. But all we're doing is keeping a cache. We'll just need to periodically dump it and rebuild it from the original entry point. That's not so bad, though.

**Comment by vendethiel** [comment]
Uh, yeah, could be one time out of 100 and that would still be okay.
Or, because we don't store anything, just ask the developer the actually restart the watcher

**Comment by michaelficarra** [comment]
Yep, that works, too. I think I'll make this watcher tool a separate repo that depends on commonjs-everywhere, which provides all of the bundling functionality.

**Comment by vendethiel** [comment]
Please do. All of us using the builder API don't really need it :).
Looking forward to that!

**Comment by michaelficarra** [comment]
@Nami-Doc: I think I'm actually going to build the watch functionality into this module's CLI instead. Changing topic and re-opening.
