### ISSUE TITLE
accept entry point over stdin when entry point filename is omitted

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#32]
<del>Give it a fake name like `entry-point.js` or simply `stdin`.</del>

**edit:** We'll probably want to just make a temporary file in the cwd, write stdin to it, bundle, then ensure the file is unlinked. Looks like we can use this: https://npmjs.org/package/mktemp

**Comment by arcanis** [comment]
The standard way to talk about stdin as a filename is `-`.

Ex : `echo foo | cat -` equals `echo foo | cat`

**Comment by michaelficarra** [comment]
@arcanis: Thanks, I went with that approach. Still considering whether I should also read from stdin if the entry file is omitted.
