### ISSUE TITLE
core module symlinks are not working on Windows

### ISSUE THREAD

**Issue by krisnye** [michaelficarra/commonjs-everywhere#39]
Trying to build a trivial module on Windows that uses the 'assert' module fails:

c:\Users\Kris\AppData\Roaming\npm\node_modules\commonjs-everywhere\lib\index.js:418
              throw e;
                    ^
Error: Core module "c:\Users\Kris\AppData\Roaming\npm\node_modules\commonjs-everywhere\core\assert.js" has not yet been
ported to the browser
    at resolvePathSync (c:\Users\Kris\AppData\Roaming\npm\node_modules\commonjs-everywhere\lib\index.js:160:15)

**Comment by michaelficarra** [comment]
How have you installed it? What happens when you run `git submodule update --init` within the commonjs-everywhere directory? Does your version of windows support symlinks? Does any version?

**Comment by krisnye** [comment]
C:\Projects\commonjs-everywhere>git submodule update --init
  Submodule 'core/node' (git://github.com/joyent/node.git) registered for path 'core/node'
  Cloning into 'core/node'...
  remote: Counting objects: 97059, done.
  remote: Compressing objects: 100% (24311/24311), done.
  remote: Total 97059 (delta 76706), reused 90651 (delta 71178)
  Receiving objects: 100% (97059/97059), 59.61 MiB | 1.97 MiB/s, done.
  Resolving deltas: 100% (76706/76706), done.
  Submodule path 'core/node': checked out '163ca274230fce536afe76c64676c332693ad7c1'

I'm using Windows 7.  Pretty sure no version of Windows supports Unix style symlinks.
This article talks about windows symlinks a bit:  http://www.tested.com/tech/windows/39-using-symlinks-in-windows-for-fun-and-profit/

I can help implement and test this for Windows if you can point me in the right direction.

**Comment by krisnye** [comment]
More info:

I installed commonjs-everywhere globally.  When I check the /core directory, it is empty, except for the node folder.

If I copy all of the *.js files from /core/node/lib into the /core directory then everything works and builds correctly and runs fine in the browser.

(I am only depending on assert.js though)

**Comment by michaelficarra** [comment]
Hmm, this might not be a Windows-only bug.

**Comment by michaelficarra** [comment]
See isaacs/npm#3310. If that doesn't get accepted, we'll have to manually list out a mapping from core modules to their commonjs-everywhere-relative locations. Gross.

**Comment by krisnye** [comment]
No manually listing would be required.  Just remove the symlinks entirely.  Change the code in resolvePathSync to check the previously symlinked location itself if the file is not found in CORE_DIR.

```
resolvePathSync = function (extensions, root, givenPath, cwd) {
    var e;
    if (isCore(givenPath)) {
        givenPath = path.resolve(path.join(CORE_DIR, '' + givenPath + '.js'));
        if (!fs.existsSync(givenPath))
            throw new Error('Core module "' + givenPath + '" has not yet been ported to the browser');
    }
    //...
}
```

**Comment by michaelficarra** [comment]
@krisnye: The symlink targets are not all in the same directory or named after the core module they replace. Some symlinks point to `core/node/lib` and others to `node_modules/some-module-that-provides-a-browser-shim/some-file`. We would need a mapping from core module name to these files. That's the purpose the symlinks currently serve.

**Comment by krisnye** [comment]
I was just thinking you might have two folders:

1 = Folder that contains custom shims named for core modules they replace.
2 = Actual core module folder.

You would check 1 for a custom shim, and if not found then just use the core file.

**Comment by michaelficarra** [comment]
@krisnye: Not all core modules are pure JS. Only the ones that are symlinked may actually be used. And we don't control the naming or locations of the custom shims. Those are npm packages in the `node_modules` directory.

**Comment by krisnye** [comment]
I see.  I guess a json mapping file then, since I doubt npm will add that symlink feature soon or ever.

**Comment by krisnye** [comment]
Let me know when a new version with this fix is pushed to npm and i'll test it.

**Comment by michaelficarra** [comment]
@krisnye: done.

https://github.com/michaelficarra/commonjs-everywhere/tree/v0.6.0
https://npmjs.org/package/commonjs-everywhere

**Comment by krisnye** [comment]
@michaelficarra This works.  Nice job.

btw-  I noticed that the installed package is about 45 Megabytes, just FYI.

**Comment by michaelficarra** [comment]
Crap, I know why. That was previously fixed, but I broke it again by moving the `node` repo. Fix coming soon.

**Comment by michaelficarra** [comment]
`0.6.1` published, 165KB.

**Comment by krisnye** [comment]
Looks like 4.7 meg now unpacked.  Probably about right with the dependencies.

**Comment by paulyoung** [comment]
Hey guys

I'm getting `Error: Core module "fs" has not yet been ported to the browser` on OSX when trying to require jquery 1.8.3

Could this be related?

**Comment by michaelficarra** [comment]
jquery must contain `require('fs')` somewhere. Does it not?

**Comment by krisnye** [comment]
try using use --ignore-missing for now, assuming you don't actually need the part of jquery that uses 'fs'

**Comment by michaelficarra** [comment]
@paulyoung: I just searched through the jQuery `1.8.3` source for a require call, and there are none. No mentions of `fs` either. If you can come up with a reproducible test case, please open a new issue.
