### ISSUE TITLE
Per file aliases

### ISSUE THREAD

**Issue by xcoderzach** [michaelficarra/commonjs-everywhere#43]
The current aliasing system does not allow for node style dependency resolution.  i.e. if module A relies on "underscore v1.3.0" and module B relies on "underscore v1.4.4" I can only require one or the other.

I realize that there are obvious issues with excess file size when including multiple versions
of the same library to the browser, however, in most cases I'd rather have extra javascript than broken libraries.

My suggestion would be to allow aliases that only apply to a single file, i.e.

``` json
{ 
fileAliases: {
  "/components/module-a/index.coffee": { 
    "underscore": "/components/module-a/components/underscore/index.js" 
  },
  "/components/module-b/index.coffee": { 
    "underscore": "/components/module-b/components/underscore/index.js" 
  }
} 
}
```

**Comment by xcoderzach** [comment]
I could implement this too if you think it's worth doing

**Comment by xcoderzach** [comment]
the reason I created this ticket is actually invalidated by what you said here:

https://github.com/michaelficarra/commonjs-everywhere/issues/42#issuecomment-16710555

I guess what I really need is a way to specify looking in /components directories so that this could be used along with bower as a way to do commonjs modules.

EDIT:

Maybe 

``` javascript
opts = { moduleDirectory: "components", packageFile: "bower.json" }
```

Let me know if this is out of the scope of this project.

Zach

**Comment by xcoderzach** [comment]
Another options could be specifying a custom resolver as an option

``` coffeescript
opts = { resolver: bowerResolver(path) }
```

**Comment by michaelficarra** [comment]
Since the topic has changed completely, I will open another issue for providing custom file resolution functions.
