### ISSUE TITLE
do something about all the duplication between sync/async versions

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#49]
Even if this forces the removal of the async versions. It's killing me.

**Comment by vendethiel** [comment]
I'm not sure why you added it in the first place ? It has worse perfs on my machine, does it improve it for you?

**Comment by michaelficarra** [comment]
Alright. If nobody says they actually use it by tomorrow, I'll drop it for `0.7`. Bring the codebase back under 300 lines.

**Comment by michaelficarra** [comment]
Alright, consider the async interface a failed experiment.

**Comment by michaelficarra** [comment]
```
$ make loc
wc -l src/*
     145 src/command.coffee
     288 src/index.coffee
     433 total
```

:smile: reasonable again.

**Comment by vendethiel** [comment]
yep, that's really great (any reason you don't `@` silence your makefile commands?)

**Comment by michaelficarra** [comment]
Send over a pull request.

**Comment by vendethiel** [comment]
Let me finish this one and I'll be all yours :).
