### ISSUE TITLE
SourceMap file not found when changing file structure

### ISSUE THREAD

**Issue by tiye** [michaelficarra/commonjs-everywhere#50]
Given file structure like:

```
➤➤ tree
.
|-- coffee
|   `-- main.coffee
|-- layout
|   `-- index.jade
`-- page
    |-- build.js
    |-- build.map
    `-- index.html
```

and I use this command to compile:

```
➤➤ cjsify -o page/build.js --source-map-file page/build.map -w coffee/main.coffee
```

(BTW, `--source-map-file` is so long to type, can we add a shortcut here?)
And I get sourceMappingURL like this:

``` js
//@ sourceMappingURL=page/build.map
```

which fails to load `build.map` since url is wrong.

This case could be bypasswd by putting both `index.html build.js` at project root directory where I run `cjsify ...`.
I tried locally that sourceMappingURL is based on the path of `.js` file,
so I think sourceMappingURL may be inferences without adding a parameter.

**Comment by michaelficarra** [comment]
Let me know how that works for you. What character do you suggest for the short form of `--source-map-file`?

**Comment by tiye** [comment]
CoffeeScript uses `-m` for sourceMap, but `-m` is taken by `--minify`, I suggest using `-s`.
And `--silent --save --short` are unlikely to appear later in `cjsify`.

**Comment by tiye** [comment]
I'm late. It works now(I tested the file structure above). Thanks for your fix :)

**Comment by michaelficarra** [comment]
Glad to hear it works fine.

**edit:** I will shorten `--source-map-file` to `--source-map` and add `-s` as a short name for it. The `-file` part is redundant in this interface.

**edit again:** 733ff9ca5fd81461b8c3fe3569cb9bea778d8611
