### ISSUE TITLE
SourceMap not working for core modules

### ISSUE THREAD

**Issue by tiye** [michaelficarra/commonjs-everywhere#51]
I used `events = require "events"` in my code.
After sourceMap generated, I found there's a `events` file in my "Sources" in dev tools.
Same for the `querystring` module if I required it.
Clicking that `events` file, I got an 404 page of Nginx(I test my pages on Nginx).
Modules installed via `npm install` works right here.

I don't know if it's reasonable enough to add sourceMap for them, but it's an issue here to report.

**Comment by michaelficarra** [comment]
Using the `--inline-sources` flag from #33 should fix this.

**Comment by michaelficarra** [comment]
@jiyinyiyong: Try using `master` and let me know if that works for you.

**Comment by tiye** [comment]
Works now, thanks :)

At first I use

```
cjsify -o build/build.js -w coffee/main.coffee -s build/build.map --inline-sources
```

and didn't work.
I found the URL a bit strange:

```
http://laptop/snowflake/build/../events
```

Later I try to use

```
cjsify -o build/build.js --inline-sources -w coffee/main.coffee -s build/build.map
```

And it works, I can see the source of `events`.

A screenshot about that(after it began to wrok.. my mouse hovering on the word `events`):
![screenshot from 2013-05-19 09 20 28](https://f.cloud.github.com/assets/449224/522338/6c5eafa0-c022-11e2-97ee-031aac86c5c1.png)

Is the URL right here?

**Comment by michaelficarra** [comment]
Everything looks as it should to me. Also, both invocations of `cjsify` work for me. How did the first one fail for you?

**Comment by tiye** [comment]
@michaelficarra When I append `--inline-sources` at the end of the command,
it just looked like there was such an argument. Nginx returned a page of `404.html`.
And that was what I found the day before.

At this moment, when open that in my browser, the code of `events` module is shown correctly.
But when I open its URL, it's stll `404.html`. Looks it makes sense, no `events` file here.

```
http://laptop/snowflake/events
```

while my project at;

```
http://laptop/snowflake/
```

Does Chrome caches the SourceMap files(I tried to clean the cache, but makes no different)?

**Comment by michaelficarra** [comment]
Since the source content is included in the source map, the URLs are not necessarily going to be served at the location shown in the developer tools. The location of the node builtins will be especially wrong. I don't think that's a problem.

**Comment by tiye** [comment]
@michaelficarra Got it. I mainly wanted to affirm the URL is noticed and not a bug.
