### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#56]
We can probably generate one. A quick google found this generator: https://github.com/jcazevedo/changelogger

**Comment by vendethiel** [comment]
I'll note that link somewhere; thanks.

**Comment by michaelficarra** [comment]
Does anyone think the changelog should be manually maintained, with more coarse change information? If so, I'll go through and remove the lines with commits that represent minor changes.

**Comment by vendethiel** [comment]
your commit messages are descriptive enough imho
