### ISSUE TITLE
Option to build a library with multiple modules and NOT define a module entry point.

### ISSUE THREAD

**Issue by krisnye** [michaelficarra/commonjs-everywhere#57]
Let me describe what would be optimal for my situation, and I think many others.

I have a module based library that I'm writing to be used primarily by web pages.

This will be use by multiple web pages which may each depend on a subset of the total modules.

I don't really want to compile the entire library into a single file per web page.

I would prefer to compile the library by specifying a list of modules (without a single entry point) into a single browser javascript file.  That file should register a global variable 'require' which enables me to access any of the modules as needed.

Html pages should be authorable with what is equivalent to my entrypoint module being an inline script like so:

```
<html>
    <head>
        <script src="mycjsify-library.js"></script>
    </head>
    <body>
        <script>
        var myModule = require("mymoduleAlpha");
        myModule.doSomethingCool();
        </script>
    </body>
</html>
```

**Comment by michaelficarra** [comment]
I think I understand what you mean. This would require a `--bare` option that omits the IIFE and exposes the internal `require` function. I think this is something we can do. I still wouldn't want to stray from the single entry point model. To specify more than one dependency and a throwaway toplevel module, just generate a bunch of `require(dependency)` calls and pass it on `stdin` as a JavaScript program.

**Comment by krisnye** [comment]
You could just take the list of modules, say ["a","b","c"] and write the entry as this, then the rest of the compilation is the same:

```
require "a"
require "b"
require "c"
global.require = require
```

I can generate that as well, and it will work, it will just be a bit cleaner as an option.

**Comment by xcoderzach** [comment]
Another advantage of exposing the internal require is that it becomes possible to use the require function from the browser console to debug modules.

**Comment by michaelficarra** [comment]
@krisnye: I woke up this morning with a similar idea. And I was reminded that exposing the internal `require` function would also force us to either do runtime module resolution (which would never happen) or to standardise on the "canonical" name that the bundle relies on internally (also unlikely). I think the best solution here is this:

``` coffee
global.require = (module) -> switch module
  when 'a' then require 'a'
  when 'b' then require 'b'
  when 'c' then require 'c'
```

That's a much safer solution and fits with the current bundling model. Closing.

**Comment by krisnye** [comment]
Note: Don't implement that as a switch, unless your sure the compiler will optimize it into a much more efficient hashtable lookup.

**Comment by michaelficarra** [comment]
Sure, something like this might be a tad bit more efficient.

``` coffee
moduleLookup = 
  a: -> require 'a'
  b: -> require 'b'
  c: -> require 'c'

global.require = (moduleName) ->
  if {}.hasOwnProperty.call moduleLookup, moduleName
  then moduleLookup[moduleName]()
  else require moduleName
```
