### ISSUE TITLE
Support input source maps when present

### ISSUE THREAD

**Issue by krisnye** [michaelficarra/commonjs-everywhere#58]
My project is authored in coffeescript (of course), and I build them with associated source.map files.

When using cjsify, it generates a source map back to the input javascript file, but does not use the .map as input.

Ideally, it should map all the way back to the original .coffee file.

Is future support for this planned, or maybe I am just missing some option.

**Comment by michaelficarra** [comment]
The `--source-map` option is a file descriptor for _output_, not input.

**Comment by krisnye** [comment]
I know.  I'm asking to also support input source maps.  Sorry if I wasn't clear enough.

**Comment by vendethiel** [comment]
Why don't you use cjs-everywhere to compile it ?

**Comment by krisnye** [comment]
Ahh, that's part of my question.  I was wondering if it would just compile the .coffee files.

I compile them to javascript already as part of building them for a nodejs environment, so the .js and .map files are already in the directories.

I don't actually specify the .js extension when specifying the input modules.  It would be nice and sufficient if the compiler just looked for .coffee files first and then used .js files if there are not .coffee files.

**Comment by krisnye** [comment]
Ok, I rearranged my project so that cjsify is compiling from directories that ONLY contain .coffee files.

I will close this request.

Still would be nice to check for .coffee files preferentially though.

**Comment by michaelficarra** [comment]
cjs-everywhere [does currently prefer `.js`](https://github.com/michaelficarra/commonjs-everywhere/blob/82562ea429017703769942495a9663f449c5bd36/src/traverse-dependencies.coffee#L32). To verify that this is the behaviour we want, I ran this experiment:

```
$ cat f.coffee
console.log 'f.coffee'
$ cat f.js
console.log('f.js');
$ node
> require('./f')
f.js
{}
>
$ node
> require('coffee-script'); undefined
undefined
> require('./f')
f.js
{}
>
```

Looks like it shouldn't change.

**Comment by krisnye** [comment]
It is true that nodejs does prefer .js files, and it is correct for it to do so.

Is it really important for cjsify to do the same though?  Seems like when there is a .coffee and a .js it would be preferable to use the one that gives source maps to the most original available source.

Doesn't really matter to me either way now since I've rearranged my project to fix the issue.
