### ISSUE TITLE
support compilers with asynchronous compilation interface

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#70]

**Comment by vendethiel** [comment]
Meh. Any you're thinking of right now?

**Comment by michaelficarra** [comment]
No, but it would be nice. I'm sure there will be one in the future.

**Comment by vendethiel** [comment]
I'm afraid it's a premature complexification, tbh. I see it making the code much more complex

**Comment by michaelficarra** [comment]
Okay, I agree.
