### ISSUE TITLE
process is an eventemitter; it should have "on", etc.

### ISSUE THREAD

**Issue by michaelficarra** [michaelficarra/commonjs-everywhere#76]

**Comment by myrne** [comment]
I made http://npmjs.org/package/process-events-shim as a stop-gap measure for browserify. Just require it and it monkey-patches the process object if it seems appropriate.

**Comment by michaelficarra** [comment]
Oh, that's cool. I will close this and recommend that anyone that needs `process` to behave as an `EventEmitter` use that module. I don't think it would be a common need, anyway, and it would be adding weight to every bundle.
