### ISSUE TITLE
.use

### ISSUE THREAD

**Issue by vendethiel** [michaelficarra/commonjs-everywhere#77]
Add something like "cjsify.use(coffeePlugin)"? Would allow for more code reuse and maybe specify them from the CLI ?

**Comment by michaelficarra** [comment]
Can you give more detail about the desired behaviour?

**Comment by vendethiel** [comment]
Hook into cjs.
Maybe add a small API for these plugins, like "addExtension", or hooks, stuff like that

**Comment by vendethiel** [comment]
Would also allow for stuff like : 

   cjsify src/entryfile.js --use cjsify-livescript,cjsify-stylus

And the CLI tool would `require()` and `.use` them, allowing to do everything from CLI.
I'm not sure we can just return JS strings from handlers atm? Might be a first step

**Comment by michaelficarra** [comment]
You [can return strings of JS from handlers](https://github.com/michaelficarra/commonjs-everywhere/blob/f9201f47321424bd353376ea4bb23ae145aff8b8/src/traverse-dependencies.coffee#L61-L67), though it's not preferred. You might want to check out the `--handler` option. You provide an extension to which it applies and the name of a module that [can be `require`d](https://github.com/michaelficarra/commonjs-everywhere/blob/f9201f47321424bd353376ea4bb23ae145aff8b8/src/command.coffee#L98-L102). Just export a function [just like the one you'd give in the `handlers` option](https://github.com/michaelficarra/commonjs-everywhere/blob/f9201f47321424bd353376ea4bb23ae145aff8b8/src/traverse-dependencies.coffee#L54-L59). I think this is what you want.

**Comment by vendethiel** [comment]
If you can specify more than one, then yes, definitely!

**Comment by michaelficarra** [comment]
Yep, just use it more than once. Closing.

**Comment by michaelficarra** [comment]
Linking to #64.

**Comment by vendethiel** [comment]
Yeah, thanks, I can't close from GH mobile
